apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx
  labels:
    app: react-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
        - name: web
          image: phucdevops/react-nginx-lab:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "120m"
              memory: "128Mi"
            limits:
              cpu: "550m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
